# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
# symbol = "â˜­"     # The "symbol" segment is being set to "â˜­"
symbol = "â˜¢"
# symbol = "â˜£"
# symbol = "âŒ¨ "
# symbol = "âŒ²"
# symbol = "â–·"

[kubernetes]
disabled = false

[line_break]
disabled = true

[time]
disabled = false
format = "ğŸ•™[ %Y-%m-%dT%H:%M:%S%.9f ]"